In [336]:
import pandas as pd

# Carregar o ficheiro CSV diretamente do ficheiro local:
df = pd.read_csv('nba.csv')

df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,$0.00,PG,$25.00,6-2,$180.00,Texas,"$7,730,337.00"
1,Jae Crowder,Boston Celtics,$99.00,SF,$25.00,6-6,$235.00,Marquette,"$6,796,117.00"
2,John Holland,Boston Celtics,$30.00,SG,$27.00,6-5,$205.00,Boston University,NaN
3,R.J. Hunter,Boston Celtics,$28.00,SG,$22.00,6-5,$185.00,Georgia State,"$1,148,640.00"
4,Jonas Jerebko,Boston Celtics,$8.00,PF,$29.00,6-10,$231.00,NaN,"$5,000,000.00"

In [337]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [338]:
# Dimensões (linhas, colunas)
print("Dimensões (linhas, colunas):", df.shape)

# Número total de elementos (linhas * colunas)
print("Número total de células/elementos:", df.size)

Dimensões (linhas, colunas): (458, 9)
Número total de células/elementos: 4122

In [339]:
# Tabela descritiva das variáveis categóricas (com display para formatar bem a tabela)
print("--- Estatísticas Descritivas (Categóricas) ---")
display(df.describe(include=['object', 'str']))

# Frequência por Posição (SG, PF, PG, SF, C)
print("\n--- Frequência por Posição ---")
print(df['Position'].value_counts())

# Frequência por Equipa (Team)
print("\n--- Frequência por Equipa ---")
print(df['Team'].value_counts())

# Proporção por Posição (%)
print("\n--- Proporção por Posição (%) ---")
print(df['Position'].value_counts(normalize=True) * 100)

--- Estatísticas Descritivas (Categóricas) ---

                 Name                  Team Position Height   College
count             457                   457      457    457       373
unique            457                    30        5     18       118
top     Avery Bradley  New Orleans Pelicans       SG    6-9  Kentucky
freq                1                    19      102     59        22

--- Frequência por Posição ---
Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

--- Frequência por Equipa ---
Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

--- Proporção por Posição (%) ---
Position
SG   $22.32
PF   $21.88
PG   $20.13
SF   $18.60
C    $17.07
Name: proportion, dtype: float64

In [340]:
# 1. Visualizar as primeiras linhas
print("--- Primeiras linhas ---")
display(df.head())

# 2. Visualizar as últimas linhas
print("--- Últimas linhas ---")
display(df.tail())

--- Primeiras linhas ---

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,$0.00,PG,$25.00,6-2,$180.00,Texas,"$7,730,337.00"
1,Jae Crowder,Boston Celtics,$99.00,SF,$25.00,6-6,$235.00,Marquette,"$6,796,117.00"
2,John Holland,Boston Celtics,$30.00,SG,$27.00,6-5,$205.00,Boston University,NaN
3,R.J. Hunter,Boston Celtics,$28.00,SG,$22.00,6-5,$185.00,Georgia State,"$1,148,640.00"
4,Jonas Jerebko,Boston Celtics,$8.00,PF,$29.00,6-10,$231.00,NaN,"$5,000,000.00"

--- Últimas linhas ---

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,$8.00,PG,$26.00,6-3,$203.00,Butler,"$2,433,333.00"
454,Raul Neto,Utah Jazz,$25.00,PG,$24.00,6-1,$179.00,NaN,"$900,000.00"
455,Tibor Pleiss,Utah Jazz,$21.00,C,$26.00,7-3,$256.00,NaN,"$2,900,000.00"
456,Jeff Withey,Utah Jazz,$24.00,C,$26.00,7-0,$231.00,Kansas,"$947,276.00"
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [341]:
df[['College']]

               College
0                Texas
1            Marquette
2    Boston University
3        Georgia State
4                  NaN
..                 ...
453             Butler
454                NaN
455                NaN
456             Kansas
457                NaN

[458 rows x 1 columns]

In [342]:
df.loc[15:20, ['Name', 'Position', 'College']]

                       Name Position         College
15         Bojan Bogdanovic       SG             NaN
16             Markel Brown       SG  Oklahoma State
17          Wayne Ellington       SG  North Carolina
18  Rondae Hollis-Jefferson       SG         Arizona
19             Jarrett Jack       PG    Georgia Tech
20           Sergey Karasev       SG             NaN

In [343]:
# Filtrar jogadores cuja posição seja exatamente 'PF'
pf_players = df[df['Position'] == 'PF']

# Visualizar o resultado
pf_players

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,$8.00,PF,$29.00,6-10,$231.00,NaN,"$5,000,000.00"
5,Amir Johnson,Boston Celtics,$90.00,PF,$29.00,6-9,$240.00,NaN,"$12,000,000.00"
6,Jordan Mickey,Boston Celtics,$55.00,PF,$21.00,6-8,$235.00,LSU,"$1,170,960.00"
24,Chris McCullough,Brooklyn Nets,$1.00,PF,$21.00,6-11,$200.00,Syracuse,"$1,140,240.00"
25,Willie Reed,Brooklyn Nets,$33.00,PF,$26.00,6-10,$220.00,Saint Louis,"$947,276.00"
...,...,...,...,...,...,...,...,...,...
435,Meyers Leonard,Portland Trail Blazers,$11.00,PF,$24.00,7-1,$245.00,Illinois,"$3,075,880.00"
441,Noah Vonleh,Portland Trail Blazers,$21.00,PF,$20.00,6-9,$240.00,Indiana,"$2,637,720.00"
442,Trevor Booker,Utah Jazz,$33.00,PF,$28.00,6-8,$228.00,Clemson,"$4,775,000.00"
446,Derrick Favors,Utah Jazz,$15.00,PF,$24.00,6-10,$265.00,Georgia Tech,"$12,000,000.00"
452,Trey Lyles,Utah Jazz,$41.00,PF,$20.00,6-10,$234.00,Kentucky,"$2,239,800.00"

In [344]:
orlando_players = df[df['Team'] == 'Orlando Magic'].drop(columns=['Team'])
orlando_players

,Name,Number,Position,Age,Height,Weight,College,Salary
354,Dewayne Dedmon,$3.00,C,$26.00,7-0,$245.00,USC,"$947,276.00"
355,Evan Fournier,$10.00,SG,$23.00,6-7,$205.00,NaN,"$2,288,205.00"
356,Aaron Gordon,$0.00,PF,$20.00,6-9,$220.00,Arizona,"$4,171,680.00"
357,Mario Hezonja,$23.00,SG,$21.00,6-8,$218.00,NaN,"$3,741,480.00"
358,Ersan Ilyasova,$7.00,PF,$29.00,6-10,$235.00,NaN,"$7,900,000.00"
359,Brandon Jennings,$55.00,PG,$26.00,6-1,$169.00,NaN,"$8,344,497.00"
360,Devyn Marble,$11.00,SF,$23.00,6-6,$200.00,Iowa,"$845,059.00"
361,Shabazz Napier,$13.00,PG,$24.00,6-1,$175.00,Connecticut,"$1,294,440.00"
362,Andrew Nicholson,$44.00,PF,$26.00,6-9,$250.00,St. Bonaventure,"$2,380,593.00"
363,Victor Oladipo,$5.00,SG,$24.00,6-4,$210.00,Indiana,"$5,192,520.00"
364,Elfrid Payton,$4.00,PG,$22.00,6-4,$185.00,Louisiana-Lafayette,"$2,505,720.00"
365,Jason Smith,$14.00,PF,$30.00,7-0,$240.00,Colorado State,"$4,300,000.00"
366,Nikola Vucevic,$9.00,C,$25.00,7-0,$260.00,USC,"$11,250,000.00"
367,C.J. Watson,$32.00,PG,$32.00,6-2,$175.00,Tennessee,"$5,000,000.00"

In [345]:
import numpy as np

def convert_to_cm(height):
    if pd.isna(height):
        return np.nan
    feet, inches = map(int, height.split('-'))
    return round((feet * 12 + inches) * 2.54, 2)

df['Height'] = df['Height'].apply(convert_to_cm)

print("Novo tipo da coluna 'Height':", df['Height'].dtype)
display(df[['Name', 'Height']].head())

Novo tipo da coluna 'Height': float64

            Name  Height
0  Avery Bradley $187.96
1    Jae Crowder $198.12
2   John Holland $195.58
3    R.J. Hunter $195.58
4  Jonas Jerebko $208.28

In [346]:
# Contar os valores nulos (NaN) em cada coluna
df.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [347]:
df = df.dropna(how='all')
print("Dimensões após remover linhas com todos os valores nulos:", df.shape)

Dimensões após remover linhas com todos os valores nulos: (457, 9)

In [348]:
df['College'] = df['College'].fillna('No College')

print("Valores nulos em College após preenchimento:", df['College'].isna().sum())

df[df['College'] == 'No College'][['Name','Team','College']].head()

Valores nulos em College após preenchimento: 0

                      Name             Team     College
4            Jonas Jerebko   Boston Celtics  No College
5             Amir Johnson   Boston Celtics  No College
15        Bojan Bogdanovic    Brooklyn Nets  No College
20          Sergey Karasev    Brooklyn Nets  No College
32  Thanasis Antetokounmpo  New York Knicks  No College

In [349]:
salary_nan = df[df['Salary'].isna()]

salary_nan[['Name', 'Team', 'Salary']]

               Name                    Team  Salary
2      John Holland          Boston Celtics     NaN
46      Elton Brand      Philadelphia 76ers     NaN
171   Dahntay Jones     Cleveland Cavaliers     NaN
264   Jordan Farmar       Memphis Grizzlies     NaN
269    Ray McCallum       Memphis Grizzlies     NaN
270  Xavier Munford       Memphis Grizzlies     NaN
273  Alex Stepheson       Memphis Grizzlies     NaN
350   Briante Weber              Miami Heat     NaN
353   Dorell Wright              Miami Heat     NaN
397    Axel Toupane          Denver Nuggets     NaN
409      Greg Smith  Minnesota Timberwolves     NaN

In [350]:
# 1. Identificar e guardar os índices das linhas que têm salário nulo
indices_nan = df[df['Salary'].isna()].index

print("--- Antes da Imputação ---")
print("Total de NaNs na coluna Salary:", df['Salary'].isna().sum())

# 2. Imputação de nível 1: Média da respetiva Equipa e Posição
df['Salary'] = df['Salary'].fillna(df.groupby(['Team', 'Position'])['Salary'].transform('mean'))

print("\n--- Após 1º Nível (Média por Team e Position) ---")
print("Total de NaNs restantes na coluna Salary:", df['Salary'].isna().sum())

# 3. Imputação de nível 2: Média global da Posição (caso sobrasse algum nulo)
df['Salary'] = df['Salary'].fillna(df.groupby('Position')['Salary'].transform('mean'))

print("\n--- Após 2º Nível (Média Global por Position) ---")
print("Total de NaNs restantes na coluna Salary:", df['Salary'].isna().sum())

# 4. Apresentar os jogadores cujos valores foram imputados (formatado em dólares)
print("\n--- Jogadores e novos salários atribuídos ---")
pd.options.display.float_format = '${:,.2f}'.format
display(df.loc[indices_nan, ['Name', 'Team', 'Position', 'Salary']])

--- Antes da Imputação ---
Total de NaNs na coluna Salary: 11

--- Após 1º Nível (Média por Team e Position) ---
Total de NaNs restantes na coluna Salary: 0

--- Após 2º Nível (Média Global por Position) ---
Total de NaNs restantes na coluna Salary: 0

--- Jogadores e novos salários atribuídos ---

               Name                    Team Position         Salary
2      John Holland          Boston Celtics       SG  $2,107,996.67
46      Elton Brand      Philadelphia 76ers       PF  $2,889,265.50
171   Dahntay Jones     Cleveland Cavaliers       SG  $3,761,809.25
264   Jordan Farmar       Memphis Grizzlies       PG  $5,144,664.00
269    Ray McCallum       Memphis Grizzlies       PG  $5,144,664.00
270  Xavier Munford       Memphis Grizzlies       PG  $5,144,664.00
273  Alex Stepheson       Memphis Grizzlies       PF  $4,435,690.80
350   Briante Weber              Miami Heat       PG $14,783,000.00
353   Dorell Wright              Miami Heat       SF  $3,460,625.50
397    Axel Toupane          Denver Nuggets       SG    $930,081.67
409      Greg Smith  Minnesota Timberwolves       PF  $4,796,280.33

In [351]:
# 1. Contagem detalhada de nulos por coluna
print("--- Nulos por Coluna ---")
print(df.isna().sum())

total_nans = df.isna().sum().sum()
print("\n--- Total Global de Nulos no DataFrame ---")
print(f"Total de NaNs restantes: {total_nans}")

# 3. Verificação lógica / asserção
if total_nans == 0:
    print("\n Sucesso: O DataFrame está completamente limpo e sem valores nulos!")
else:
    print(f"\n Atenção: Ainda existem {total_nans} valores nulos por tratar.")

--- Nulos por Coluna ---
Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

--- Total Global de Nulos no DataFrame ---
Total de NaNs restantes: 0

 Sucesso: O DataFrame está completamente limpo e sem valores nulos!

In [352]:
contingency_table =  pd.crosstab(df['Team'], df['Position'], margins=True, margins_name="Total")
display(contingency_table)

Position                 C   PF  PG  SF   SG  Total
Team
Atlanta Hawks            3    4   2   2    4     15
Boston Celtics           3    3   4   1    4     15
Brooklyn Nets            2    4   3   0    6     15
Charlotte Hornets        3    3   3   1    5     15
Chicago Bulls            2    5   2   2    4     15
Cleveland Cavaliers      3    2   3   2    5     15
Dallas Mavericks         3    4   4   2    2     15
Denver Nuggets           3    2   3   3    4     15
Detroit Pistons          3    2   4   4    2     15
Golden State Warriors    3    2   2   5    3     15
Houston Rockets          2    4   2   3    4     15
Indiana Pacers           2    4   4   3    2     15
Los Angeles Clippers     2    3   3   4    3     15
Los Angeles Lakers       3    4   3   4    1     15
Memphis Grizzlies        1    6   5   3    3     18
Miami Heat               1    4   2   5    3     15
Milwaukee Bucks          2    3   4   3    4     16
Minnesota Timberwolves   3    4   3   3    1     14
New Orleans Pelicans     3    3   4   4    5     19
New York Knicks          2    4   2   4    4     16
Oklahoma City Thunder    3    3   2   3    4     15
Orlando Magic            2    4   4   1    3     14
Philadelphia 76ers       2    5   4   2    2     15
Phoenix Suns             3    2   4   3    3     15
Portland Trail Blazers   3    3   2   2    5     15
Sacramento Kings         3    2   2   4    4     15
San Antonio Spurs        4    2   3   2    4     15
Toronto Raptors          3    4   3   3    2     15
Utah Jazz                3    3   4   3    2     15
Washington Wizards       3    2   2   4    4     15
Total                   78  100  92  85  102    457

In [353]:
df_sorted = df.sort_values(by=['College', 'Age'], ascending=[True, False])

display(df_sorted[['College', 'Age', 'Name', 'Team', 'Position']].head(15))

     College    Age                     Name                   Team Position
180  Alabama $33.00              Mo Williams    Cleveland Cavaliers       PG
287  Alabama $29.00               Alonzo Gee   New Orleans Pelicans       SF
266  Alabama $25.00           JaMychal Green      Memphis Grizzlies       PF
256  Arizona $38.00              Jason Terry        Houston Rockets       SG
170  Arizona $35.00        Richard Jefferson    Cleveland Cavaliers       SF
167  Arizona $33.00            Channing Frye    Cleveland Cavaliers       PF
83   Arizona $32.00           Andre Iguodala  Golden State Warriors       SF
123  Arizona $28.00           Chase Budinger           Phoenix Suns       SF
201  Arizona $28.00              Jordan Hill         Indiana Pacers        C
212  Arizona $27.00           Jerryd Bayless        Milwaukee Bucks       PG
44   Arizona $25.00         Derrick Williams        New York Knicks       PF
202  Arizona $25.00             Solomon Hill         Indiana Pacers       SF
54   Arizona $24.00           T.J. McConnell     Philadelphia 76ers       PG
18   Arizona $21.00  Rondae Hollis-Jefferson          Brooklyn Nets       SG
192  Arizona $20.00          Stanley Johnson        Detroit Pistons       SF

In [354]:
age_stats = df.groupby('Position')['Age'].describe()
display(age_stats)

           count   mean   std    min    25%    50%    75%    max
Position
C         $78.00 $27.37 $4.16 $20.00 $24.00 $27.00 $30.00 $40.00
PF       $100.00 $27.16 $4.61 $20.00 $24.00 $27.00 $30.00 $40.00
PG        $92.00 $26.85 $4.17 $20.00 $24.00 $26.50 $30.00 $40.00
SF        $85.00 $26.86 $4.39 $20.00 $23.00 $26.00 $29.00 $38.00
SG       $102.00 $26.54 $4.64 $19.00 $23.00 $25.00 $29.75 $39.00

In [355]:
# 1. Contar o número de equipas únicas
num_teams = df['Team'].nunique()
print(f"Número total de equipas: {num_teams}")

# 2. Obter e visualizar a lista de nomes das equipas (ordenadas alfabeticamente)
team_names = sorted(df['Team'].unique())
print("\nLista de equipas:")
for i, team in enumerate(team_names, 1):
    print(f"{i:2d}. {team}")

Número total de equipas: 30

Lista de equipas:
 1. Atlanta Hawks
 2. Boston Celtics
 3. Brooklyn Nets
 4. Charlotte Hornets
 5. Chicago Bulls
 6. Cleveland Cavaliers
 7. Dallas Mavericks
 8. Denver Nuggets
 9. Detroit Pistons
10. Golden State Warriors
11. Houston Rockets
12. Indiana Pacers
13. Los Angeles Clippers
14. Los Angeles Lakers
15. Memphis Grizzlies
16. Miami Heat
17. Milwaukee Bucks
18. Minnesota Timberwolves
19. New Orleans Pelicans
20. New York Knicks
21. Oklahoma City Thunder
22. Orlando Magic
23. Philadelphia 76ers
24. Phoenix Suns
25. Portland Trail Blazers
26. Sacramento Kings
27. San Antonio Spurs
28. Toronto Raptors
29. Utah Jazz
30. Washington Wizards

In [356]:
# Contar o número de jogadores por equipa
players_by_team = df['Team'].value_counts()

# Visualizar o resultado
print(players_by_team)

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [357]:
players_by_position = df['Position'].value_counts()
print(players_by_position)

Position
SG    102
PF    100
PG     92
SF     85
C      78
Name: count, dtype: int64

In [358]:
# Obter os 10 jogadores com maior salário
top10_salary = df.nlargest(10, 'Salary')[['Name', 'Team', 'Position', 'Salary']]

# Visualizar a tabela formatada
display(top10_salary)

                Name                   Team Position         Salary
109      Kobe Bryant     Los Angeles Lakers       SF $25,000,000.00
169     LeBron James    Cleveland Cavaliers       SF $22,970,500.00
33   Carmelo Anthony        New York Knicks       SF $22,875,000.00
251    Dwight Howard        Houston Rockets        C $22,359,364.00
339       Chris Bosh             Miami Heat       PF $22,192,730.00
100       Chris Paul   Los Angeles Clippers       PG $21,468,695.00
414     Kevin Durant  Oklahoma City Thunder       SF $20,158,622.00
164     Derrick Rose          Chicago Bulls       PG $20,093,064.00
349      Dwyane Wade             Miami Heat       SG $20,000,000.00
23       Brook Lopez          Brooklyn Nets        C $19,689,000.00

In [359]:
# Calcular a média das duas colunas
mean_stats = df[['Age', 'Salary']].mean()

print(mean_stats)

Age             $26.94
Salary   $4,841,216.31
dtype: float64

In [360]:
# 1. Calcular as médias de referência
avg_age = df['Age'].mean()
avg_salary = df['Salary'].mean()

print(f"Critérios: Idade < {avg_age:.2f} anos e Salário > ${avg_salary:,.2f}\n")

# 2. Filtrar jogadores que cumprem ambas as condições
young_and_rich = df[(df['Age'] < avg_age) & (df['Salary'] > avg_salary)]

# 3. Ordenar por Age e Salary (por exemplo, Idade crescente e Salário decrescente)
sorted_young_rich = young_and_rich.sort_values(
    by=['Age', 'Salary'],
    ascending=[True, False]
)[['Name', 'Team', 'Position', 'Age', 'Salary']]

# 4. Apresentar o número total e os primeiros registos
print(f"Total de jogadores encontrados: {len(sorted_young_rich)}")
display(sorted_young_rich)

Critérios: Idade < 26.94 anos e Salário > $4,841,216.31

Total de jogadores encontrados: 50

,Name,Team,Position,Age,Salary
410,Karl-Anthony Towns,Minnesota Timberwolves,C,$20.00,"$5,703,600.00"
116,D'Angelo Russell,Los Angeles Lakers,PG,$20.00,"$5,103,120.00"
411,Andrew Wiggins,Minnesota Timberwolves,SG,$21.00,"$5,758,680.00"
223,Jabari Parker,Milwaukee Bucks,PF,$21.00,"$5,152,440.00"
332,Michael Kidd-Gilchrist,Charlotte Hornets,SF,$22.00,"$6,331,404.00"
369,Bradley Beal,Washington Wizards,SG,$22.00,"$5,694,674.00"
189,Tobias Harris,Detroit Pistons,SF,$23.00,"$16,000,000.00"
350,Briante Weber,Miami Heat,PG,$23.00,"$14,783,000.00"
281,Anthony Davis,New Orleans Pelicans,PF,$23.00,"$7,070,730.00"
168,Kyrie Irving,Cleveland Cavaliers,PG,$24.00,"$16,407,501.00"
301,Kawhi Leonard,San Antonio Spurs,SF,$24.00,"$16,407,500.00"
418,Enes Kanter,Oklahoma City Thunder,C,$24.00,"$16,407,500.00"
219,Khris Middleton,Milwaukee Bucks,SG,$24.00,"$14,700,000.00"
127,Brandon Knight,Phoenix Suns,PG,$24.00,"$13,500,000.00"
446,Derrick Favors,Utah Jazz,PF,$24.00,"$12,000,000.00"
444,Alec Burks,Utah Jazz,SG,$24.00,"$9,463,484.00"
66,Cory Joseph,Toronto Raptors,PG,$24.00,"$7,000,000.00"
363,Victor Oladipo,Orlando Magic,SG,$24.00,"$5,192,520.00"
269,Ray McCallum,Memphis Grizzlies,PG,$24.00,"$5,144,664.00"
270,Xavier Munford,Memphis Grizzlies,PG,$24.00,"$5,144,664.00"
425,Dion Waiters,Oklahoma City Thunder,SG,$24.00,"$5,138,430.00"
143,DeMarcus Cousins,Sacramento Kings,C,$25.00,"$15,851,950.00"
382,John Wall,Washington Wizards,PG,$25.00,"$15,851,950.00"
179,Tristan Thompson,Cleveland Cavaliers,C,$25.00,"$14,260,870.00"
407,Ricky Rubio,Minnesota Timberwolves,PG,$25.00,"$12,700,000.00"
366,Nikola Vucevic,Orlando Magic,C,$25.00,"$11,250,000.00"
290,Jrue Holiday,New Orleans Pelicans,PG,$25.00,"$10,595,507.00"
272,Lance Stephenson,Memphis Grizzlies,SF,$25.00,"$9,000,000.00"
177,Iman Shumpert,Cleveland Cavaliers,SG,$25.00,"$8,988,765.00"
428,Al-Farouq Aminu,Portland Trail Blazers,SF,$25.00,"$8,042,895.00"
0,Avery Bradley,Boston Celtics,PG,$25.00,"$7,730,337.00"
1,Jae Crowder,Boston Celtics,SF,$25.00,"$6,796,117.00"
160,Nikola Mirotic,Chicago Bulls,PF,$25.00,"$5,543,725.00"
199,Paul George,Indiana Pacers,SF,$26.00,"$17,120,106.00"
153,Jimmy Butler,Chicago Bulls,SG,$26.00,"$16,407,500.00"
220,Greg Monroe,Milwaukee Bucks,C,$26.00,"$16,407,500.00"
249,James Harden,Houston Rockets,SG,$26.00,"$15,756,438.00"
89,Klay Thompson,Golden State Warriors,SG,$26.00,"$15,501,000.00"
448,Gordon Hayward,Utah Jazz,SF,$26.00,"$15,409,570.00"
82,Draymond Green,Golden State Warriors,PF,$26.00,"$14,260,870.00"
191,Reggie Jackson,Detroit Pistons,PG,$26.00,"$13,913,044.00"
121,Eric Bledsoe,Phoenix Suns,PG,$26.00,"$13,500,000.00"
417,Serge Ibaka,Oklahoma City Thunder,PF,$26.00,"$12,250,000.00"
336,Kemba Walker,Charlotte Hornets,PG,$26.00,"$12,000,000.00"
387,Kenneth Faried,Denver Nuggets,PF,$26.00,"$11,235,955.00"
285,Tyreke Evans,New Orleans Pelicans,SG,$26.00,"$10,734,586.00"
64,DeMar DeRozan,Toronto Raptors,SG,$26.00,"$10,050,000.00"
359,Brandon Jennings,Orlando Magic,PG,$26.00,"$8,344,497.00"
376,Markieff Morris,Washington Wizards,PF,$26.00,"$8,000,000.00"
194,Marcus Morris,Detroit Pistons,PF,$26.00,"$5,000,000.00"

In [361]:
# 1. Calcular a média salarial por equipa
team_avg_salary = df.groupby('Team')['Salary'].mean()

# 2. Equipa com o maior salário médio
highest_team = team_avg_salary.idxmax()
highest_val = team_avg_salary.max()

# 3. Equipa com o menor salário médio
lowest_team = team_avg_salary.idxmin()
lowest_val = team_avg_salary.min()

print("--- Equipa com Maior e Menor Salário Médio ---")
print(f"Maior média: {highest_team} com ${highest_val:,.2f}")
print(f"Menor média: {lowest_team} com ${lowest_val:,.2f}")

# 4. As três equipas com maior salário médio
top3_teams = team_avg_salary.nlargest(3)

print("\n--- Top 3 Equipas com Maior Média Salarial ---")
for rank, (team, salary) in enumerate(top3_teams.items(), 1):
    print(f"{rank}. {team}: ${salary:,.2f}")

--- Equipa com Maior e Menor Salário Médio ---
Maior média: Cleveland Cavaliers com $7,383,366.55
Menor média: Philadelphia 76ers com $2,258,810.63

--- Top 3 Equipas com Maior Média Salarial ---
1. Cleveland Cavaliers: $7,383,366.55
2. Miami Heat: $6,717,286.57
3. Los Angeles Clippers: $6,323,642.67

In [362]:
# Obter o índice da linha com maior salário em cada equipa
idx_max_salary = df.groupby('Team')['Salary'].idxmax()

# Selecionar essas linhas completas no DataFrame original
top_player_per_team = df.loc[idx_max_salary, ['Team', 'Name', 'Position', 'Salary']].sort_values(by='Team')

display(top_player_per_team)

                       Team               Name Position         Salary
315           Atlanta Hawks       Paul Millsap       PF $18,671,659.00
5            Boston Celtics       Amir Johnson       PF $12,000,000.00
23            Brooklyn Nets        Brook Lopez        C $19,689,000.00
330       Charlotte Hornets       Al Jefferson        C $13,500,000.00
164           Chicago Bulls       Derrick Rose       PG $20,093,064.00
169     Cleveland Cavaliers       LeBron James       SF $22,970,500.00
233        Dallas Mavericks    Wesley Matthews       SG $16,407,500.00
388          Denver Nuggets   Danilo Gallinari       SF $14,000,000.00
189         Detroit Pistons      Tobias Harris       SF $16,000,000.00
89    Golden State Warriors      Klay Thompson       SG $15,501,000.00
251         Houston Rockets      Dwight Howard        C $22,359,364.00
199          Indiana Pacers        Paul George       SF $17,120,106.00
100    Los Angeles Clippers         Chris Paul       PG $21,468,695.00
109      Los Angeles Lakers        Kobe Bryant       SF $25,000,000.00
265       Memphis Grizzlies         Marc Gasol        C $19,688,000.00
339              Miami Heat         Chris Bosh       PF $22,192,730.00
220         Milwaukee Bucks        Greg Monroe        C $16,407,500.00
407  Minnesota Timberwolves        Ricky Rubio       PG $12,700,000.00
288    New Orleans Pelicans        Eric Gordon       SG $15,514,031.00
33          New York Knicks    Carmelo Anthony       SF $22,875,000.00
414   Oklahoma City Thunder       Kevin Durant       SF $20,158,622.00
366           Orlando Magic     Nikola Vucevic        C $11,250,000.00
52       Philadelphia 76ers        Carl Landry       PF  $6,500,000.00
121            Phoenix Suns       Eric Bledsoe       PG $13,500,000.00
428  Portland Trail Blazers    Al-Farouq Aminu       SF  $8,042,895.00
143        Sacramento Kings   DeMarcus Cousins        C $15,851,950.00
294       San Antonio Spurs  LaMarcus Aldridge       PF $19,689,000.00
63          Toronto Raptors    DeMarre Carroll       SF $13,600,000.00
448               Utah Jazz     Gordon Hayward       SF $15,409,570.00
382      Washington Wizards          John Wall       PG $15,851,950.00

In [363]:
# 1. Resumo estatístico completo do salário por posição
salary_stats_by_pos = df.groupby('Position')['Salary'].describe()

# Formatar a apresentação dos números da tabela
pd.options.display.float_format = '${:,.2f}'.format
print("--- Estatísticas de Salário por Posição ---")
display(salary_stats_by_pos)

# 2. Identificar a posição com o maior salário médio
mean_salaries = df.groupby('Position')['Salary'].mean()
highest_pos = mean_salaries.idxmax()
highest_pos_val = mean_salaries.max()

print(f"\nPosição com maior salário médio: {highest_pos} (${highest_pos_val:,.2f})")

--- Estatísticas de Salário por Posição ---

,count,mean,std,min,25%,50%,75%,max
Position,,,,,,,,
C,$78.00,"$5,967,052.00","$5,787,988.91","$83,397.00","$1,328,880.00","$3,811,060.00","$9,620,558.25","$22,359,364.00"
PF,$100.00,"$4,546,820.87","$4,729,805.97","$111,444.00","$1,123,722.25","$2,971,610.50","$5,543,725.00","$22,192,730.00"
PG,$92.00,"$5,185,499.60","$5,042,069.86","$55,722.00","$1,448,610.00","$3,106,518.00","$7,100,703.00","$21,468,695.00"
SF,$85.00,"$4,840,960.02","$5,977,916.80","$30,888.00","$1,000,000.00","$2,041,080.00","$5,500,000.00","$25,000,000.00"
SG,$102.00,"$3,958,589.66","$4,438,804.26","$55,722.00","$947,276.00","$2,117,918.33","$5,675,000.00","$20,000,000.00"

Posição com maior salário médio: C ($5,967,052.00)